// User actions
export const USER = {
  SET_AUTHENTICATED: 'SET_AUTHENTICATED',
  SET_USER: 'SET_USER',
  RESET_USER: 'RESET_USER',
  SET_LIGHTBOX: 'SET_LIGHTBOX',
};

// User email actions
export const USER_EMAIL = { SET_USER_EMAIL: 'SET_USER_EMAIL' };

// Loading actions
export const LOADING_STATE = {
  SET_LOADING_STATUS: 'SET_LOADING_STATUS',
};

// Locations actions
export const LOCATIONS = {
  GET_LOCATIONS: 'GET_LOCATIONS',
  SET_LOCATIONS: 'SET_LOCATIONS',
  SET_LOCATION: 'SET_LOCATION',
};

// Locations actions
export const TILES = {
  GET_TILES: 'GET_TILES',
  SET_TILES: 'SET_TILES',
};

// Deals actions
export const DEALS = {
  GET_DEALS: 'GET_DEALS',
  SET_DEALS: 'SET_DEALS',
  SET_EXTRA_DEALS: 'SET_EXTRA_DEALS',
  SET_NO_MORE_DEALS: 'SET_NO_MORE_DEALS',
  SET_LAST_ID: 'SET_LAST_ID',
  SET_ONLY_MAIN_DEAL: 'SET_ONLY_MAIN_DEAL',
  SET_WITHOUT_MAIN_DEAL: 'SET_WITHOUT_MAIN_DEAL',
  SET_RECOMMENDED_DEALS: 'SET_RECOMMENDED_DEALS',
  SET_NEW_PRODUCT_DEALS: 'SET_NEW_PRODUCT_DEALS',
  SET_RECENTLY_VIEWED_DEALS: 'SET_RECENTLY_VIEWED_DEALS',
  SET_ALL_FEATURED_DEALS_LOADED: 'SET_ALL_FEATURED_DEALS_LOADED',
};

// Sroller deals
export const SCROLLER = { SET_SCROLLER: 'SET_SCROLLER' };

// Navigation Menu
export const NAVIGATION = {
  SET_SSR: 'SET_NAVIGATION_SSR',
  SET_MENU: 'SET_MENU',
  SET_DEAL_PREVIEW: 'SET_DEAL_PREVIEW',
};

// New Products
export const NEWPRODUCTS = { SET_NEWPRODUCTS: 'SET_NEWPRODUCTS' };

//Search results, query and suggestions
export const SEARCH = {
  SEARCH_QUERY: 'SEARCH_QUERY',
  SEARCH_RESULTS: 'SEARCH_RESULTS',
  SEARCH_SUGGESTIONS: 'SEARCH_SUGGESTIONS',
  SEARCH_IS_LOADING: 'SEARCH_IS_LOADING',
  SEARCH_PANEL_VISIBILITY: 'SEARCH_PANEL_VISIBILITY',
};
// Basket actions
export const BASKET = {
  SET_BASKET: 'SET_BASKET',
  RESET_BASKET: 'RESET_BASKET',
};

// checkout actions
export const CHECKOUT = {
  SET_CHECKOUT: 'SET_CHECKOUT',
  SET_CHECKOUT_STATUS: 'SET_CHECKOUT_STATUS',
  RESET_COUNTDOWN: 'CHECKOUT_RESET_COUNTDOWN',
  CHECKOUT_API_PARAMS: 'CHECKOUT_API_PARAMS',
};

// Wallet
export const WALLET = {
  SET_WALLET: 'SET_WALLET',
  ERROR_WALLET: 'ERROR_WALLET',
  RESET_WALLET: 'RESET_WALLET',
};

// Filters
export const FILTERS = {
  EMPTY_FILTERS: 'EMPTY_FILTERS',
  GET_FILTERS: 'GET_FILTERS',
  SET_FILTERS: 'SET_FILTERS',
  SET_NO_MORE_FILTERS: 'SET_NO_MORE_FILTERS',
  RESET_FILTERS: 'RESET_FILTERS',
  SET_EXTRA_FILTERS: 'SET_EXTRA_FILTERS',
  SET_URL_PATH: 'SET_URL_PATH',
};

// Gifting
export const GIFTING = {
  SET_GIFTING: 'SET_GIFTING',
  RESET_GIFTING: 'RESET_GIFTING',
};

// video playback
export const VIDEO = {
  SET_VISIBILITY: 'SET_VIDEO_VISIBILITY',
  SET_AUTO_PLAYABLE: 'SET_VIDEO_AUTO_PLAYABLE',
  PLAY: 'VIDEO_PLAYING',
  STOP: 'VIDEO_STOP',
};

// Page type
export const PAGE_TYPE = { SET_PAGE_TYPE: 'SET_PAGE_TYPE' };
